<?php 
$books = $this->getCollection();
if(!$books) return;
?>
<div class="flipbooks">
<?php foreach ($books as $book): ?>
	<div class="book-details">
		<div class="book-thumb">
			<div class="flip-book effect">
				<span class="guide"><a href="<?php echo $this->getUrl('flipbook/index/book', array('id' => $book->getEntityId())); ?>"><?= __('Click Here To Open Book') ?></a></span>
		    	<a href="<?php echo $this->getUrl('flipbook/index/book', array('id' => $book->getEntityId())); ?>"><?php echo $this->getThumbnail($book); ?></a>
		  	</div>
		</div>
		<h2 class="book-title"><?php echo $book->getTitle(); ?></h2>
		<h3 class="book-author"><?php echo $book->getAuthor(); ?></h3>
		<div class="book-description"><?php echo $book->getDescription(); ?></div>
	</div>
<?php endforeach; ?>
</div>